# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
      env:
        "AllowedHosts": "*"
        "ConnectionStrings": ""
        "ConnectionStrings:SqlServer": "Data Source=localhost,1433;Initial Catalog=payment;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=True"
        "Kafka": ""
        "Kafka:Broker": "localhost:29092"
        "Kafka:GroupId": "ecommerce-gp"
        "Kafka:Topic1": "payment"
        "Logging": ""
        "Logging:LogLevel": ""
        "Logging:LogLevel:Default": "Information"
        "Logging:LogLevel:Microsoft.AspNetCore": "Warning"
    - name: Install dependencies
      run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
